package com.hd.agent.storage.model;

import com.hd.agent.basefiles.model.GoodsInfo;

import java.io.Serializable;
import java.math.BigDecimal;

public class LendDetail implements Serializable {
    /**
     * 编号
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 单据编号
     *
     * @mbggenerated
     */
    private String billid;

    /**
     * 批次现存量编号
     *
     * @mbggenerated
     */
    private String summarybatchid;

    /**
     * 商品编号
     *
     * @mbggenerated
     */
    private String goodsid;

    /**
     * 商品详情
     */
    private GoodsInfo goodsInfo;

    /**
     * 品牌编号
     *
     * @mbggenerated
     */
    private String brandid;

    /**
     * 主计量单位
     *
     * @mbggenerated
     */
    private String unitid;

    /**
     * 主计量单位名称
     *
     * @mbggenerated
     */
    private String unitname;

    /**
     * 数量
     *
     * @mbggenerated
     */
    private BigDecimal unitnum;

    /**
     * 辅计量单位
     *
     * @mbggenerated
     */
    private String auxunitid;

    /**
     * 辅计量单位名称
     *
     * @mbggenerated
     */
    private String auxunitname;

    /**
     * 数量(辅单位整数数量)
     *
     * @mbggenerated
     */
    private BigDecimal auxnum;

    /**
     * 辅单位余数数量（主单位换算后剩余数量）
     *
     * @mbggenerated
     */
    private BigDecimal auxremainder;

    /**
     * 数量(辅计量显示)
     *
     * @mbggenerated
     */
    private String auxnumdetail;

    /**
     * 合计箱数
     *
     * @mbggenerated
     */
    private BigDecimal totalbox;

    /**
     * 含税单价
     *
     * @mbggenerated
     */
    private BigDecimal taxprice;

    /**
     * 含税金额
     *
     * @mbggenerated
     */
    private BigDecimal taxamount;

    /**
     * 无税单价
     *
     * @mbggenerated
     */
    private BigDecimal notaxprice;

    /**
     * 无税金额
     *
     * @mbggenerated
     */
    private BigDecimal notaxamount;

    /**
     * 税种
     *
     * @mbggenerated
     */
    private String taxtype;

    /**
     * 税额
     *
     * @mbggenerated
     */
    private BigDecimal tax;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 仓库编码
     *
     * @mbggenerated
     */
    private String storageid;

    /**
     * 库位
     *
     * @mbggenerated
     */
    private String storagelocationid;

    /**
     * 批次号
     *
     * @mbggenerated
     */
    private String batchno;

    /**
     * 生产日期
     *
     * @mbggenerated
     */
    private String produceddate;

    /**
     * 有效截止日期
     *
     * @mbggenerated
     */
    private String deadline;

    /**
     * 排序
     *
     * @mbggenerated
     */
    private Integer seq;

    private String lendtype;

    private String lendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_storage_lend_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getLendtype() {
        return lendtype;
    }

    public void setLendtype(String lendtype) {
        this.lendtype = lendtype;
    }

    public String getLendid() {
        return lendid;
    }

    public void setLendid(String lendid) {
        this.lendid = lendid;
    }

    /**
     * 编号
     * @return  id  编号
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 编号
     * @param  id  编号
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 单据编号
     * @return  billid  单据编号
     *
     * @mbggenerated
     */
    public String getBillid() {
        return billid;
    }

    /**
     * 单据编号
     * @param  billid  单据编号
     *
     * @mbggenerated
     */
    public void setBillid(String billid) {
        this.billid = billid == null ? null : billid.trim();
    }

    /**
     * 批次现存量编号
     * @return  summarybatchid  批次现存量编号
     *
     * @mbggenerated
     */
    public String getSummarybatchid() {
        return summarybatchid;
    }

    /**
     * 批次现存量编号
     * @param  summarybatchid  批次现存量编号
     *
     * @mbggenerated
     */
    public void setSummarybatchid(String summarybatchid) {
        this.summarybatchid = summarybatchid == null ? null : summarybatchid.trim();
    }

    /**
     * 商品编号
     * @return  goodsid  商品编号
     *
     * @mbggenerated
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * 商品编号
     * @param  goodsid  商品编号
     *
     * @mbggenerated
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid == null ? null : goodsid.trim();
    }

    /**
     * 品牌编号
     * @return  brandid  品牌编号
     *
     * @mbggenerated
     */
    public String getBrandid() {
        return brandid;
    }

    /**
     * 品牌编号
     * @param  brandid  品牌编号
     *
     * @mbggenerated
     */
    public void setBrandid(String brandid) {
        this.brandid = brandid == null ? null : brandid.trim();
    }

    /**
     * 主计量单位
     * @return  unitid  主计量单位
     *
     * @mbggenerated
     */
    public String getUnitid() {
        return unitid;
    }

    /**
     * 主计量单位
     * @param  unitid  主计量单位
     *
     * @mbggenerated
     */
    public void setUnitid(String unitid) {
        this.unitid = unitid == null ? null : unitid.trim();
    }

    /**
     * 主计量单位名称
     * @return  unitname  主计量单位名称
     *
     * @mbggenerated
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * 主计量单位名称
     * @param  unitname  主计量单位名称
     *
     * @mbggenerated
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname == null ? null : unitname.trim();
    }

    /**
     * 数量
     * @return  unitnum  数量
     *
     * @mbggenerated
     */
    public BigDecimal getUnitnum() {
        return unitnum;
    }

    /**
     * 数量
     * @param  unitnum  数量
     *
     * @mbggenerated
     */
    public void setUnitnum(BigDecimal unitnum) {
        this.unitnum = unitnum;
    }

    /**
     * 辅计量单位
     * @return  auxunitid  辅计量单位
     *
     * @mbggenerated
     */
    public String getAuxunitid() {
        return auxunitid;
    }

    /**
     * 辅计量单位
     * @param  auxunitid  辅计量单位
     *
     * @mbggenerated
     */
    public void setAuxunitid(String auxunitid) {
        this.auxunitid = auxunitid == null ? null : auxunitid.trim();
    }

    /**
     * 辅计量单位名称
     * @return  auxunitname  辅计量单位名称
     *
     * @mbggenerated
     */
    public String getAuxunitname() {
        return auxunitname;
    }

    /**
     * 辅计量单位名称
     * @param  auxunitname  辅计量单位名称
     *
     * @mbggenerated
     */
    public void setAuxunitname(String auxunitname) {
        this.auxunitname = auxunitname == null ? null : auxunitname.trim();
    }

    /**
     * 数量(辅单位整数数量)
     * @return  auxnum  数量(辅单位整数数量)
     *
     * @mbggenerated
     */
    public BigDecimal getAuxnum() {
        return auxnum;
    }

    /**
     * 数量(辅单位整数数量)
     * @param  auxnum  数量(辅单位整数数量)
     *
     * @mbggenerated
     */
    public void setAuxnum(BigDecimal auxnum) {
        this.auxnum = auxnum;
    }

    /**
     * 辅单位余数数量（主单位换算后剩余数量）
     * @return  auxremainder  辅单位余数数量（主单位换算后剩余数量）
     *
     * @mbggenerated
     */
    public BigDecimal getAuxremainder() {
        return auxremainder;
    }

    /**
     * 辅单位余数数量（主单位换算后剩余数量）
     * @param  auxremainder  辅单位余数数量（主单位换算后剩余数量）
     *
     * @mbggenerated
     */
    public void setAuxremainder(BigDecimal auxremainder) {
        this.auxremainder = auxremainder;
    }

    /**
     * 数量(辅计量显示)
     * @return  auxnumdetail  数量(辅计量显示)
     *
     * @mbggenerated
     */
    public String getAuxnumdetail() {
        return auxnumdetail;
    }

    /**
     * 数量(辅计量显示)
     * @param  auxnumdetail  数量(辅计量显示)
     *
     * @mbggenerated
     */
    public void setAuxnumdetail(String auxnumdetail) {
        this.auxnumdetail = auxnumdetail == null ? null : auxnumdetail.trim();
    }

    /**
     * 合计箱数
     * @return  totalbox  合计箱数
     *
     * @mbggenerated
     */
    public BigDecimal getTotalbox() {
        return totalbox;
    }

    /**
     * 合计箱数
     * @param  totalbox  合计箱数
     *
     * @mbggenerated
     */
    public void setTotalbox(BigDecimal totalbox) {
        this.totalbox = totalbox;
    }

    /**
     * 含税单价
     * @return  taxprice  含税单价
     *
     * @mbggenerated
     */
    public BigDecimal getTaxprice() {
        return taxprice;
    }

    /**
     * 含税单价
     * @param  taxprice  含税单价
     *
     * @mbggenerated
     */
    public void setTaxprice(BigDecimal taxprice) {
        this.taxprice = taxprice;
    }

    /**
     * 含税金额
     * @return  taxamount  含税金额
     *
     * @mbggenerated
     */
    public BigDecimal getTaxamount() {
        return taxamount;
    }

    /**
     * 含税金额
     * @param  taxamount  含税金额
     *
     * @mbggenerated
     */
    public void setTaxamount(BigDecimal taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * 无税单价
     * @return  notaxprice  无税单价
     *
     * @mbggenerated
     */
    public BigDecimal getNotaxprice() {
        return notaxprice;
    }

    /**
     * 无税单价
     * @param  notaxprice  无税单价
     *
     * @mbggenerated
     */
    public void setNotaxprice(BigDecimal notaxprice) {
        this.notaxprice = notaxprice;
    }

    /**
     * 无税金额
     * @return  notaxamount  无税金额
     *
     * @mbggenerated
     */
    public BigDecimal getNotaxamount() {
        return notaxamount;
    }

    /**
     * 无税金额
     * @param  notaxamount  无税金额
     *
     * @mbggenerated
     */
    public void setNotaxamount(BigDecimal notaxamount) {
        this.notaxamount = notaxamount;
    }

    /**
     * 税种
     * @return  taxtype  税种
     *
     * @mbggenerated
     */
    public String getTaxtype() {
        return taxtype;
    }

    /**
     * 税种
     * @param  taxtype  税种
     *
     * @mbggenerated
     */
    public void setTaxtype(String taxtype) {
        this.taxtype = taxtype == null ? null : taxtype.trim();
    }

    /**
     * 税额
     * @return  tax  税额
     *
     * @mbggenerated
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * 税额
     * @param  tax  税额
     *
     * @mbggenerated
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * 备注
     * @return  remark  备注
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     * @param  remark  备注
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 仓库编码
     * @return  storageid  仓库编码
     *
     * @mbggenerated
     */
    public String getStorageid() {
        return storageid;
    }

    /**
     * 仓库编码
     * @param  storageid  仓库编码
     *
     * @mbggenerated
     */
    public void setStorageid(String storageid) {
        this.storageid = storageid == null ? null : storageid.trim();
    }

    /**
     * 库位
     * @return  storagelocationid  库位
     *
     * @mbggenerated
     */
    public String getStoragelocationid() {
        return storagelocationid;
    }

    /**
     * 库位
     * @param  storagelocationid  库位
     *
     * @mbggenerated
     */
    public void setStoragelocationid(String storagelocationid) {
        this.storagelocationid = storagelocationid == null ? null : storagelocationid.trim();
    }

    /**
     * 批次号
     * @return  batchno  批次号
     *
     * @mbggenerated
     */
    public String getBatchno() {
        return batchno;
    }

    /**
     * 批次号
     * @param  batchno  批次号
     *
     * @mbggenerated
     */
    public void setBatchno(String batchno) {
        this.batchno = batchno == null ? null : batchno.trim();
    }

    /**
     * 生产日期
     * @return  produceddate  生产日期
     *
     * @mbggenerated
     */
    public String getProduceddate() {
        return produceddate;
    }

    /**
     * 生产日期
     * @param  produceddate  生产日期
     *
     * @mbggenerated
     */
    public void setProduceddate(String produceddate) {
        this.produceddate = produceddate == null ? null : produceddate.trim();
    }

    /**
     * 有效截止日期
     * @return  deadline  有效截止日期
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * 有效截止日期
     * @param  deadline  有效截止日期
     *
     * @mbggenerated
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline == null ? null : deadline.trim();
    }

    /**
     * 排序
     * @return  seq  排序
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * 排序
     * @param  seq  排序
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
    public GoodsInfo getGoodsInfo() {
        return goodsInfo;
    }

    public void setGoodsInfo(GoodsInfo goodsInfo) {
        this.goodsInfo = goodsInfo;
    }
}