KindEditor.lang({
	zdiv:'自定义div块',
	zinputhidden:'隐藏域',
	zinputtext:'单行文本',
	zmultitext:'多行文本',
	zselect:'下拉框',
	zcheckbox:'多选框',
	zradio:'单选框',
	zdictionary:'编码字典',
	zusers:'人员选择器',
	zdepart:'部门选择器',
	zmacro:'宏控件'
});